-- =============================================
-- Y2O Project - Full Database Setup
-- Run this file once to create all tables.
-- =============================================

-- Users
CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255),
    password_hash character varying(255),
    first_name character varying(100),
    last_name character varying(100),
    phone_number character varying(20),
    role character varying(50),
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

-- =============================================
-- Onboarding Profile Tables
-- =============================================

CREATE SEQUENCE IF NOT EXISTS public.student_profiles_id_seq;

CREATE TABLE IF NOT EXISTS public.student_profiles
(
    id bigint NOT NULL DEFAULT nextval('student_profiles_id_seq'::regclass),
    age integer,
    grade character varying(50),
    school character varying(255),
    school_board character varying(255),
    top_interests character varying[],
    primary_goal character varying(255),
    user_id bigint,
    CONSTRAINT student_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT fk_user FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE SEQUENCE IF NOT EXISTS public.parent_profiles_id_seq;

CREATE TABLE IF NOT EXISTS public.parent_profiles
(
    id bigint NOT NULL DEFAULT nextval('parent_profiles_id_seq'::regclass),
    teen_email character varying(255),
    primary_focus character varying(255),
    user_id bigint,
    CONSTRAINT parent_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT fk_user FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE SEQUENCE IF NOT EXISTS public.organization_profiles_id_seq;

CREATE TABLE IF NOT EXISTS public.organization_profiles
(
    id bigint NOT NULL DEFAULT nextval('organization_profiles_id_seq'::regclass),
    org_name character varying(255),
    org_type character varying(100),
    org_size character varying(50),
    org_role character varying(100),
    primary_goal character varying(255),
    user_id bigint,
    CONSTRAINT organization_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT fk_user FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- =============================================
-- Profile Page Tables
-- =============================================

CREATE TABLE IF NOT EXISTS public.user_profiles
(
    id bigint NOT NULL,
    name character varying(255),
    headline character varying(255),
    location character varying(255),
    about text,
    profile_pic character varying(500),
    CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT fk_profile_user FOREIGN KEY (id)
        REFERENCES public.users (id)
        ON DELETE CASCADE
);

CREATE SEQUENCE IF NOT EXISTS public.education_id_seq;

CREATE TABLE IF NOT EXISTS public.education
(
    id bigint NOT NULL DEFAULT nextval('education_id_seq'::regclass),
    user_id bigint NOT NULL,
    title character varying(255),
    description text,
    CONSTRAINT education_pkey PRIMARY KEY (id),
    CONSTRAINT fk_education_user FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON DELETE CASCADE
);

CREATE SEQUENCE IF NOT EXISTS public.projects_id_seq;

CREATE TABLE IF NOT EXISTS public.projects
(
    id bigint NOT NULL DEFAULT nextval('projects_id_seq'::regclass),
    user_id bigint NOT NULL,
    project_name character varying(255),
    description text,
    CONSTRAINT projects_pkey PRIMARY KEY (id),
    CONSTRAINT fk_projects_user FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON DELETE CASCADE
);