-- =============================================
-- Y2O Project - Full Database Setup
-- Run this file once to create all tables.
-- =============================================

-- Users
CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255),
    password_hash character varying(255),
    first_name character varying(100),
    last_name character varying(100),
    phone_number character varying(20),
    role character varying(50),
    created_at timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

-- Sequences required by profile tables
CREATE SEQUENCE IF NOT EXISTS public.student_profiles_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.parent_profiles_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.organization_profiles_id_seq;

-- Student profiles
CREATE TABLE IF NOT EXISTS public.student_profiles
(
    id bigint NOT NULL DEFAULT nextval('student_profiles_id_seq'::regclass),
    age integer,
    grade character varying(50),
    school character varying(255),
    school_board character varying(255),
    top_interests character varying[],
    primary_goal character varying(255),
    user_id bigint,
    CONSTRAINT student_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT fk_user FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- Parent profiles
CREATE TABLE IF NOT EXISTS public.parent_profiles
(
    id bigint NOT NULL DEFAULT nextval('parent_profiles_id_seq'::regclass),
    teen_email character varying(255),
    primary_focus character varying(255),
    user_id bigint,
    CONSTRAINT parent_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT fk_user FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- Organization profiles
CREATE TABLE IF NOT EXISTS public.organization_profiles
(
    id bigint NOT NULL DEFAULT nextval('organization_profiles_id_seq'::regclass),
    org_name character varying(255),
    org_type character varying(100),
    org_size character varying(50),
    org_role character varying(100),
    primary_goal character varying(255),
    user_id bigint,
    CONSTRAINT organization_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT fk_user FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);
